default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: no-commit-to-branch
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pyproject
          - flake8-import-order
          - flake8-builtins
          - flake8-annotations
          - flake8-quotes
          - flake8-simplify
          - flake8-bugbear
  - repo: http://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--check]